# Generated by Django 3.2.25 on 2025-07-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugrecommendation',
            name='approvedby',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drugrecommendation',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
