# Generated by Django 3.2.25 on 2025-07-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20250724_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating_review',
            name='rating',
            field=models.FloatField(),
        ),
    ]
