# Generated by Django 3.2.25 on 2025-07-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_rating_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
