# Generated by Django 3.2.25 on 2025-07-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_doctor_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='languages_known',
            field=models.CharField(default='English', max_length=50),
        ),
    ]
