# Generated by Django 3.2.25 on 2025-07-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_doctor_languages_known'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='State_Medical_Council',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='languages_known',
            field=models.CharField(default='English', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
    ]
