# Generated by Django 3.2.25 on 2025-07-31 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20250731_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='diseaseinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.diseaseinfo'),
        ),
    ]
