# Generated by Django 3.2.25 on 2025-08-01 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_consultation_diseaseinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugrecommendation',
            name='approvedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.doctor'),
        ),
    ]
