# Generated by Django 3.2.25 on 2025-08-05 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_drugrecommendation_approvedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugrecommendation',
            name='approvedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_drugrecommendations', to='main_app.doctor'),
        ),
        migrations.AlterField(
            model_name='drugrecommendation',
            name='updatedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_drugrecommendations', to='main_app.doctor'),
        ),
    ]
