# Generated by Django 3.2.25 on 2025-07-26 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20250724_1600'),
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_patient_clear', models.BooleanField()),
                ('was_prediction_accurate', models.BooleanField()),
                ('patient_followed_advice', models.BooleanField()),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('comment', models.TextField()),
                ('rating', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.consultation')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='PatientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_chat_help', models.BooleanField()),
                ('was_prediction_useful', models.BooleanField()),
                ('patient_followed_advice', models.BooleanField()),
                ('felt_more_confident', models.BooleanField()),
                ('recommend_others', models.BooleanField()),
                ('suggestions', models.TextField()),
                ('allow_public', models.BooleanField(default=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.consultation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
