# Generated by Django 3.2.25 on 2025-07-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20250726_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorfeedback',
            name='patient_followed_advice',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='doctorfeedback',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='doctorfeedback',
            name='was_patient_clear',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='doctorfeedback',
            name='was_prediction_accurate',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patientfeedback',
            name='felt_more_confident',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patientfeedback',
            name='patient_followed_advice',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patientfeedback',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='patientfeedback',
            name='recommend_others',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patientfeedback',
            name='suggestions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientfeedback',
            name='was_chat_help',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patientfeedback',
            name='was_prediction_useful',
            field=models.BooleanField(null=True),
        ),
    ]
